### PR TITLE
Rebuild

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
This should solve issues like https://github.com/conda-forge/dicttoxml-feedstock/issues/2

**Comment by jan-janssen** [comment]
Or failing builds like https://github.com/conda-forge/pyiron_base-feedstock/pull/51

**Comment by maresb** [comment]
Wonderful!!! #2 has been annoying me for quite a long time.

Can you give any insight into what was the problem? And what in particular was the solution? (Based on your commit, it looks to me like you essentially remade the whole feedstock.)

**Comment by jan-janssen** [comment]
The only thing I did was rerendering the recipe. In the first commit I only increased the build number.

**Pull request merged**
